version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "node-recipes"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1t7mcughf268l"
s3_prefix = "node-recipes"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
