AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Recipes REST API
Globals:
  Function:
    Timeout: 3
Resources:
  # RecipesApiGateway:
  #   Type: AWS::Serverless::Api
  #   Properties:
  #     Name: Gateway Endpoint Recipes Resource
  #     StageName: Prod
  #   Cors:
  #     AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
  #     AllowHeaders: "'X-Forwarded-For'"
  #     MaxAge: "'600'"
  #     AllowOrigin: "'*'"
  #     AllowCredentials: True
  ListRecipesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: listRecipes/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies: 
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /recipes
            Method: get
  GetRecipeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getRecipe/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies: 
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBReadOnlyAccess
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /recipes/{id}
            Method: get
  CreateRecipeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: createRecipe/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies: 
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /recipes
            Method: post
  UpdateRecipeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: updateRecipe/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies: 
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /recipes/{id}
            Method: put
  DeleteRecipeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: deleteRecipe/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies: 
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /recipes/{id}
            Method: delete
